# Generated by Django 4.2.13 on 2026-06-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_capacity_to_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
