# Generated by Django 4.2.13 on 2026-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_timeslot_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='discussion_topic',
            field=models.CharField(blank=True, help_text='What this time slot is best suited for', max_length=200),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Zoom, Teams, or other meeting URL'),
        ),
    ]
