# Generated by Django 4.2.13 on 2026-06-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_timeslot_discussion_topic_timeslot_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Weekdays available for this slot', max_length=50),
        ),
    ]
